-- AlterEnum (add new event types, remove TRIVIA)
BEGIN;
CREATE TYPE "EventType_new" AS ENUM ('MUSIC', 'DJ', 'OPEN_MIC', 'COMEDY', 'THEATER', 'GAMES', 'KARAOKE', 'PRIVATE', 'FILM', 'SPOKEN_WORD', 'DANCE', 'MARKET', 'WORKSHOP', 'PARTY', 'FITNESS', 'DRAG', 'OTHER');
ALTER TABLE "events" ALTER COLUMN "eventType" TYPE "EventType_new" USING ("eventType"::text::"EventType_new");
ALTER TYPE "EventType" RENAME TO "EventType_old";
ALTER TYPE "EventType_new" RENAME TO "EventType";
DROP TYPE "public"."EventType_old";
COMMIT;

-- AlterTable: Add region clustering fields
ALTER TABLE "regions" ADD COLUMN "centroidLat" DOUBLE PRECISION;
ALTER TABLE "regions" ADD COLUMN "centroidLng" DOUBLE PRECISION;
ALTER TABLE "regions" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
