/**
 * Delete auto-generated regions
 * Run with: npx tsx scripts/delete-auto-regions.ts
 */

import 'dotenv/config'
import prisma from '../server/utils/prisma'

async function main() {
  // First unlink venues from auto-generated regions
  const regions = await prisma.region.findMany({
    where: { isAutoGenerated: true },
    select: { id: true }
  })
  const regionIds = regions.map(r => r.id)

  const unlinked = await prisma.venue.updateMany({
    where: { regionId: { in: regionIds } },
    data: { regionId: null }
  })
  console.log('Unlinked', unlinked.count, 'venues from regions')

  // Now delete the regions
  const deleted = await prisma.region.deleteMany({
    where: { isAutoGenerated: true }
  })
  console.log('Deleted', deleted.count, 'auto-generated regions')
  await prisma.$disconnect()
}

main().catch(console.error)
